### ISSUE TITLE
When I run my own dataset, I get the following Error. What might be the cause?

### ISSUE THREAD

**Issue by DongShengze** [JSB-UCLA/scDesign2#7]
This dataset works on both splatter and zinb-wave, but it didn't work when I followed the tutorial simulation of a single type of cell:

> copula_result <- fit_model_scDesign2(data_mat, 'type', sim_method = 'copula')
Error in pnbinom(gene, size = param[2], mu = param[3]) : 
  数学函数中用了非数值参数
此外: There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
警告信息：
1: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
2: In sqrt(1/i) : 产生了NaNs
3: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
4: In sqrt(1/i) : 产生了NaNs
5: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
6: In sqrt(1/i) : 产生了NaNs
7: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
8: In sqrt(1/i) : 产生了NaNs
9: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
10: In sqrt(1/i) : 产生了NaNs
11: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
12: In sqrt(1/i) : 产生了NaNs
13: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
14: In sqrt(1/i) : 产生了NaNs
15: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
16: In sqrt(1/i) : 产生了NaNs
17: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
18: In sqrt(1/i) : 产生了NaNs
19: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
20: In sqrt(1/i) : 产生了NaNs
21: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
22: In sqrt(1/i) : 产生了NaNs
23: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
24: In sqrt(1/i) : 产生了NaNs
25: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
26: In sqrt(1/i) : 产生了NaNs
27: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
28: In sqrt(1/i) : 产生了NaNs
29: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
30: In sqrt(1/i) : 产生了NaNs
31: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
32: In sqrt(1/i) : 产生了NaNs
33: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
34: In sqrt(1/i) : 产生了NaNs
35: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
36: In sqrt(1/i) : 产生了NaNs
37: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
38: In sqrt(1/i) : 产生了NaNs
39: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
40: In sqrt(1/i) : 产生了NaNs
41: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
42: In sqrt(1/i) : 产生了NaNs
43: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
44: In sqrt(1/i) : 产生了NaNs
45: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
46: In sqrt(1/i) : 产生了NaNs
47: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
48: In sqrt(1/i) : 产生了NaNs
49: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached
50: In sqrt(1/i) : 产生了NaNs

If you can provide some tips or help, I would really appreciate it!

**Comment by JSB-UCLA** [comment]
Please provide your input dataset or its exact format, and I hope my
student Qingyang can help address the issue you encountered or suggest
whether scDesign3 can help.

Best,
Jessica

**Comment by DongShengze** [comment]
Thanks a lot for your reply!




Please check the dataset that attached to this email. What I'm providing is a float array, and when I use it, I'm rounding it to integer. This is a gene subset of the original dataset, containing 2000 hypervariable genes with a total of 1422 samples. All samples share the same cell-type. I want to generate an equal number of samples with scDesign2. My error may have been due to my lack of experience with R, but I didn't know what to do. I would appreciate it if you could give me some help.
















At 2024-10-23 22:22:02, "Junction of Statistics and Biology" ***@***.***> wrote:

Please provide your input dataset or its exact format, and I hope my
student Qingyang can help address the issue you encountered or suggest
whether scDesign3 can help.

Best,
Jessica

**Comment by JSB-UCLA** [comment]
Please directly send an email to me ***@***.***) and Qingyang Wang (
***@***.***) with your example dataset and R code. I couldn't see your
attachment in the comment. Thanks!

Best,
Jessica

**Comment by DongShengze** [comment]
I'm sorry but I could not see the email address, they were masked by the website. I have uploaded the file in this comment, maybe you can check that this time. Thank you for your patience.
[fibroblast_float.zip](https://github.com/user-attachments/files/17500939/fibroblast_float.zip)

**Comment by qw130** [comment]
Hi @DongShengze,

Thank you for pointing out this bug. It has been fixed in the latest code. Please let me know if you have any further questions.

Best,
Qingyang

**Comment by DongShengze** [comment]
@qw130  Thanks for your update! My problems have been fixed.
